version: "3.8"

services: 
  # React app
  olm_app:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    ports: 
      - 3000:3000
    volumes:
      - .:/app/olm_app
      - /app/olm_app/node_modules
    networks: 
      - app

networks:
  app:
    driver: bridge
